version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "80:8001" # Cambiamos el segundo 80 para cada servicio
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./:/app
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./:/app
